apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasource-deployment
  labels:
    app: datasource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasource-postgres
  template:
    metadata:
      labels:
        app: datasource-postgres
    spec:
      containers:
        - name: datasource-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: datasource-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP