spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: postgres
    password: 12345
  jpa:
      hibernate:
       ddl-auto: update
  redis:
      host: redis
      port: 6379

server:
  port: 8081