spring:
  application:
    name: credit-account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379

server:
  port: 8082

customer:
  customer-url: http://customer-service:8081/customer/